version: "3.9"

services:
  pokedexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGO_DB: ${MONGO_DB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      # volumes:
      #   - ./:/var/www/pokedex

  db:                       # nos conectamos a la base de datos de un container
    image: mongo:6.0.6
    container_name: mongo-poke
    restart: always
    ports:
    - 27020:27017           # local: container
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db